### PR TITLE
Update bundling-prebuilt.md

### PR DESCRIPTION
**Pull request by Misplon**
Resolves https://github.com/siteorigin/docs/issues/56.

### CODE REVIEW

**Comment by Misplon** [comment]
@AlexGStapleton I'm going to merge to get the updated info live but please, take a look when ready and let me know if you'd like any changes.

**Comment by AlexGStapleton** [comment]
Looks good. 👍 
Due to the complex nature of this change, it might be a good idea to provide an example plugin for reference.

**Comment by Misplon** [comment]
Thanks, please, give my changes a once over https://github.com/siteorigin/docs/blob/develop/page-builder/bundling-prebuilt.md

**Comment by AlexGStapleton** [comment]
I've left a comment regarding SiteOrigin Corp, but outside of that it looks good.

**Comment by Misplon** [comment]
Thanks. Done. We can make further adjustments based on any feedback we get. Just let me know if anything gets raised as not being clear.

**Pull request merged**
