### PR TITLE
I added a sub section to : Filtering Page Builder Widgets

### PR DESCRIPTION
**Pull request by mamarmite**
I just searched that and found a little to add widget into recommended sections.

I called it : Add widgets to recommended group

Anyhow, I would have found that useful. Hopes it follow the code style and language.

Thanks.

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
Hi @mamarmite,

Thank you for your PR. There are a few concepts introduced in this PR that should really be separated. The separated headings would look like this:

- `Add a widget to the recommended Group` (your current code without the loop)
- `Adding Multiple Widgets at once (your code as is)
- `Maintain Standard Widget Ordering` (a brief paragraph mentioning filter priorities).

Would you like to give that a shot? If not, I can make the changes for you if you would prefer.

Kind regards,
Alex

**Comment by mamarmite** [comment]
@AlexGStapleton  Sorry for the silence radio. I finaly got the time to seperate the pull request in the structure you've suggest :)
Let me know if there is anything, typo, error, etc.

Thanks and have a good day

**Comment by AlexGStapleton** [comment]
Hi @mamarmite,

Sorry for the delay.

I've made some adjustments to ensure the code maintains WordPress coding standards (this is something we're trying to do with all new code added), and the text is a little more technical.

Kind regards,
Alex

**Review by AlexGStapleton — APPROVED** [review]

**Comment by Misplon** [comment]
Hi @mamarmite, thanks for your help, appreciate it!

**Pull request merged**
